conversion:
  buy-rate: 0.5    # 1 currency = 0.5 reputation points
  sell-rate: 0.2   # 1 currency = 0.2 reputation points

traders:
  - amy
  - brick
  - jake

permissions:
  amy:
    - permission: trader.buy.sword
      min: 10
    - permission: trader.sell.armor
      min: 20
  brick:
    - permission: trader.buy.potion
      min: 5
